#!/usr/bin/env node

/**
 * Growthovo Setup Wizard
 * Interactive setup script to configure your app
 */

const readline = require('readline');
const fs = require('fs');
const path = require('path');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

function question(prompt) {
  return new Promise((resolve) => {
    rl.question(prompt, resolve);
  });
}

async function main() {
  console.log('\n🚀 Growthovo Setup Wizard\n');
  console.log('This script will help you configure your app.\n');

  // Check if .env exists
  const envPath = path.join(__dirname, 'ascevo', '.env');
  const envExists = fs.existsSync(envPath);

  if (envExists) {
    console.log('✅ .env file already exists\n');
    const overwrite = await question('Do you want to reconfigure it? (y/n): ');
    if (overwrite.toLowerCase() !== 'y') {
      console.log('\n✅ Keeping existing configuration');
      rl.close();
      return;
    }
  }

  console.log('\n📝 Let\'s set up your Supabase credentials\n');
  console.log('If you don\'t have a Supabase project yet:');
  console.log('1. Go to https://supabase.com/dashboard');
  console.log('2. Click "New project"');
  console.log('3. Name it "growthovo" and set a password');
  console.log('4. Wait 2-3 minutes for it to be created');
  console.log('5. Go to Settings → API to get your keys\n');

  const hasProject = await question('Do you have a Supabase project ready? (y/n): ');
  
  if (hasProject.toLowerCase() !== 'y') {
    console.log('\n⏸️  Please create a Supabase project first, then run this script again.');
    console.log('Run: node setup-wizard.js\n');
    rl.close();
    return;
  }

  console.log('\n');
  const supabaseUrl = await question('Enter your Supabase Project URL: ');
  const supabaseKey = await question('Enter your Supabase anon public key: ');

  console.log('\n🤔 Optional: OpenAI API Key (for Rex AI chat)');
  console.log('   If you skip this, Rex will use fallback responses.\n');
  const hasOpenAI = await question('Do you want to add OpenAI key now? (y/n): ');
  
  let openaiKey = '';
  if (hasOpenAI.toLowerCase() === 'y') {
    openaiKey = await question('Enter your OpenAI API key: ');
  }

  // Create .env content
  const envContent = `# ============================================================================
# GROWTHOVO - ENVIRONMENT CONFIGURATION
# ============================================================================
# Auto-generated by setup-wizard.js
# ============================================================================

# ----------------------------------------------------------------------------
# 🔵 SUPABASE - Database, Auth, Storage (REQUIRED)
# ----------------------------------------------------------------------------
EXPO_PUBLIC_SUPABASE_URL=${supabaseUrl}
EXPO_PUBLIC_SUPABASE_ANON_KEY=${supabaseKey}

# ----------------------------------------------------------------------------
# 🤖 OPENAI - AI Features (OPTIONAL)
# ----------------------------------------------------------------------------
${openaiKey ? `OPENAI_API_KEY=${openaiKey}` : '# OPENAI_API_KEY=sk-proj-...'}

# ----------------------------------------------------------------------------
# 💳 STRIPE - Payments (OPTIONAL - Add later)
# ----------------------------------------------------------------------------
# EXPO_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_test_...
# EXPO_PUBLIC_STRIPE_PRICE_MONTHLY=price_...
# EXPO_PUBLIC_STRIPE_PRICE_ANNUAL=price_...

# ----------------------------------------------------------------------------
# ⚙️ FEATURE FLAGS
# ----------------------------------------------------------------------------
EXPO_PUBLIC_ENABLE_PWA=true
NODE_ENV=development
EXPO_PUBLIC_ENV=development
`;

  // Write .env file
  fs.writeFileSync(envPath, envContent);
  console.log('\n✅ .env file created successfully!\n');

  // Show next steps
  console.log('📋 Next Steps:\n');
  console.log('1. Setup Database:');
  console.log('   → Open Supabase Dashboard: https://supabase.com/dashboard');
  console.log('   → Click SQL Editor → New query');
  console.log('   → Copy content from: ascevo/supabase/schema.sql');
  console.log('   → Paste and click RUN\n');
  
  console.log('2. Run Migrations:');
  console.log('   → In SQL Editor, run these files in order:');
  console.log('     • ascevo/supabase/migrations/003_mascot_evolution_system.sql');
  console.log('     • ascevo/supabase/migrations/20240020_ascevo_features_v3.sql');
  console.log('     • ascevo/supabase/migrations/20240030_daily_os_core.sql\n');
  
  console.log('3. Load Seed Data:');
  console.log('   → In SQL Editor, run: ascevo/supabase/seed.sql\n');
  
  console.log('4. Enable Real-time:');
  console.log('   → Go to Database → Replication');
  console.log('   → Enable: user_mascot_progress, xp_transactions\n');
  
  console.log('5. Start Your App:');
  console.log('   → cd ascevo');
  console.log('   → npm start');
  console.log('   → Press "w" for web\n');

  console.log('💡 Tip: I\'ve created a file "ascevo/setup-database.sql" that combines');
  console.log('   all the SQL you need to run. Copy and paste that into Supabase!\n');

  // Create combined SQL file
  await createCombinedSQLFile();

  console.log('✅ Setup complete! Follow the steps above.\n');
  
  rl.close();
}

async function createCombinedSQLFile() {
  const sqlFiles = [
    'ascevo/supabase/schema.sql',
    'ascevo/supabase/migrations/003_mascot_evolution_system.sql',
    'ascevo/supabase/migrations/20240001_rex_cache.sql',
    'ascevo/supabase/migrations/20240002_ai_usage.sql',
    'ascevo/supabase/migrations/20240020_ascevo_features_v3.sql',
    'ascevo/supabase/migrations/20240030_daily_os_core.sql',
    'ascevo/supabase/seed.sql',
  ];

  let combinedSQL = `-- ============================================================================
-- GROWTHOVO - COMBINED DATABASE SETUP
-- ============================================================================
-- Auto-generated by setup-wizard.js
-- Run this entire file in Supabase SQL Editor
-- ============================================================================

`;

  for (const file of sqlFiles) {
    const filePath = path.join(__dirname, file);
    if (fs.existsSync(filePath)) {
      const content = fs.readFileSync(filePath, 'utf8');
      const fileName = path.basename(file);
      combinedSQL += `\n-- ============================================================================\n`;
      combinedSQL += `-- FILE: ${fileName}\n`;
      combinedSQL += `-- ============================================================================\n\n`;
      combinedSQL += content;
      combinedSQL += `\n\n`;
    }
  }

  const outputPath = path.join(__dirname, 'ascevo', 'setup-database.sql');
  fs.writeFileSync(outputPath, combinedSQL);
  console.log('✅ Created: ascevo/setup-database.sql (combined SQL file)\n');
}

main().catch(console.error);
