-- ============================================================
-- FITNESS PILLAR (Pillar 02) - All 40 Lessons
-- ============================================================
-- Generated from FITNESS_LESSONS_COMPLETE.md
-- UUID Scheme:
--   Units:   22222222-0200-00UU-0000-000000000000 (UU = 01-05)
--   Lessons: 33333333-0200-00UU-0000-00000000000L (UU = unit 01-05, L = lesson 1-8)
--
-- Pillar ID: 11111111-0000-0000-0000-000000000002 (Fitness)
-- Run AFTER schema.sql, rls.sql, and seed.sql

-- ============================================================
-- FITNESS UNITS
-- ============================================================
INSERT INTO units (id, pillar_id, title, display_order) VALUES
  ('22222222-0200-0001-0000-000000000000', '11111111-0000-0000-0000-000000000002', 'Movement Foundations', 1),
  ('22222222-0200-0002-0000-000000000000', '11111111-0000-0000-0000-000000000002', 'Strength Building', 2),
  ('22222222-0200-0003-0000-000000000000', '11111111-0000-0000-0000-000000000002', 'Cardio & Endurance', 3),
  ('22222222-0200-0004-0000-000000000000', '11111111-0000-0000-0000-000000000002', 'Nutrition Basics', 4),
  ('22222222-0200-0005-0000-000000000000', '11111111-0000-0000-0000-000000000002', 'Recovery & Longevity', 5);

-- ============================================================
-- FITNESS — Unit 1: Movement Foundations
-- ============================================================
INSERT INTO lessons (id, unit_id, title, display_order, card_concept, card_example, card_mistake, card_science, card_challenge) VALUES
('33333333-0200-0001-0000-000000000001','22222222-0200-0001-0000-000000000000','Why Your Body Was Built to Move',1,
'Your body isn''t designed for sitting — it''s designed for movement. Humans evolved walking 15-20 kilometers per day hunting and gathering. Your muscles, joints, and cardiovascular system all deteriorate without regular movement, not because you''re aging, but because you''re not using them. Sitting for 8 hours a day is like keeping a sports car in a garage and wondering why the engine seizes. Movement isn''t optional exercise — it''s basic maintenance for the machine you live in. The question isn''t "should I move?" but "how did I convince myself I could survive without it?"',
'Liam, 22, worked a desk job and gamed in the evenings. By 10pm his back hurt, his neck was stiff, and he felt 40. He started walking 10 minutes every 2 hours during work. No gym, no equipment, just walking. After 2 weeks, his back pain reduced by half. After a month, it was gone. His boss asked what changed. He said: "I stopped pretending sitting all day was normal. My body needed to move." Six months later, he walks 10,000 steps daily without thinking about it. He says he has more energy at 10pm than he did at 10am before.',
'Thinking you''ll start moving when you have time, energy, or motivation. You won''t. Movement creates energy — it doesn''t require it. Waiting until you feel like exercising means you''ll wait forever. The tired, stiff feeling you have? That''s not from too much movement. It''s from too little. Your body interprets constant sitting as preparation for shutdown. When you don''t move, your brain assumes you don''t need to and allocates energy elsewhere. Start moving and the energy follows within days, not the other way around.',
'Research from the University of Queensland shows that sitting for more than 6 hours daily increases mortality risk by 40% compared to sitting less than 3 hours — even in people who exercise regularly. The mechanism: prolonged sitting reduces lipoprotein lipase activity (the enzyme that breaks down fat in the blood) by 90%, raises blood sugar, and increases inflammatory markers. Movement — even light walking — reactivates these systems within minutes. Your body wasn''t built for stillness. It was built to move, and it breaks down when you don''t.',
'Set a timer for 2 hours from now. When it goes off, stand up and walk for 5 minutes — around your room, your office, outside, anywhere. Doesn''t matter how fast. Just move continuously for 5 minutes. Do this 3 times today. Notice how your body feels at the end of the day compared to a normal sitting day. That difference is what movement does.'),

('33333333-0200-0001-0000-000000000002','22222222-0200-0001-0000-000000000000','The 5-Minute Movement Habit',2,
'Five minutes of movement is infinitely more than zero. Most people don''t start moving because they think "what''s the point of 5 minutes?" The point is: 5 minutes breaks the inertia. The hardest part of movement isn''t the movement — it''s the transition from not moving to moving. Five minutes is enough to reset your metabolism, shift your mood, and prove to yourself you can do it. It''s not a compromise. It''s the foundation. Build the 5-minute habit first. Everything else compounds from there.',
'Sofia, 20, tried to go to the gym 5 times a week. She went twice, felt guilty, quit. She switched to 5 minutes of movement every morning — stretching, walking, dancing, anything. No exceptions. If she had time for more, great. If not, 5 minutes counted. After a month, she naturally started going longer because the habit was built. After 3 months, she was moving 30 minutes most days without it feeling forced. She said the shift happened when she stopped trying to be perfect and started trying to be consistent. Five minutes every day beat 60 minutes twice a week.',
'Thinking short movement sessions "don''t count" unless they''re intense or long. This all-or-nothing thinking is why most people do nothing. Five minutes of walking is better for your metabolism, mood, and energy than sitting for 5 minutes telling yourself you''ll exercise later. Consistency beats intensity for building habits. The goal in the first month isn''t fitness — it''s proving to yourself that you''re someone who moves every day. Once that identity is built, the duration increases naturally.',
'Research from the University of Utah shows that even 1-2 minute movement breaks every hour reduce mortality risk by 33% and improve insulin sensitivity measurably. The mechanism: brief movement activates muscle glucose uptake and increases blood flow to the brain, both of which decline within 30 minutes of sitting. Your body responds to frequency as much as duration. Five minutes 6 times per day produces more metabolic benefit than 30 minutes once. Movement habits are built in minutes, not hours.',
'Right now, set a timer for 5 minutes. Move in any way — walk, stretch, dance, squats, anything that gets your body moving. When the timer goes off, you''re done. That''s it. Do this at the same time every day this week. Notice that 5 minutes is both easier than you thought and more impactful than you expected.'),

('33333333-0200-0001-0000-000000000003','22222222-0200-0001-0000-000000000000','Sitting Is Not the New Smoking (But It''s Still Bad)',3,
'The headline "sitting is the new smoking" is clickbait, but the research behind it is real. Sitting for prolonged periods increases risk of heart disease, diabetes, and early death — not because sitting is poison, but because your body shuts down metabolic processes it doesn''t think you need. Blood flow slows, glucose regulation weakens, muscles atrophy. The fix isn''t to never sit — it''s to never sit for more than an hour without moving. Your body can handle sitting. It can''t handle sitting for 8 hours straight. Break it up.',
'Marcus, 24, sat for 10+ hours daily between work and gaming. His doctor told him his cholesterol and blood sugar were pre-diabetic at 24. He started standing and walking for 2 minutes every hour. No other changes. Three months later, both numbers dropped into normal range. His doctor asked if he''d changed his diet. He hadn''t. He''d just stopped sitting continuously. He said the hardest part was remembering to stand. Once it became automatic, his body responded within weeks. He''s 25 now. His numbers are better than they were at 22.',
'Thinking that working out 3 times a week "cancels out" 8 hours of daily sitting. It doesn''t. Exercise and movement are not the same thing. Exercise builds fitness. Movement maintains metabolic function. You can be fit and still experience the negative effects of prolonged sitting — your metabolism doesn''t care that you ran 5k this morning if you''ve been sitting for 6 hours since. The goal is exercise and frequent movement, not one or the other.',
'A study published in the Annals of Internal Medicine found that the negative health impacts of prolonged sitting are partially independent of physical activity levels — meaning even people who exercise regularly show increased disease risk if they sit for extended periods. The mechanism: sitting for more than 60 minutes continuously reduces blood flow to the legs by up to 50%, triggers inflammatory responses, and reduces insulin sensitivity. Standing or walking for 2 minutes per hour reverses these effects almost completely.',
'For the next 8 hours, set an alarm for every 60 minutes. When it goes off, stand up and move for 2 minutes minimum. Walk, stretch, do squats, anything. Track how many you complete. At the end of the day, write down how you feel compared to a normal full-sitting day. That contrast is the cost of continuous sitting.'),

('33333333-0200-0001-0000-000000000004','22222222-0200-0001-0000-000000000000','Basic Mobility - Unlocking Stiff Joints',4,
'Stiffness isn''t age — it''s lack of use. Your joints are designed to move through their full range of motion daily. When you don''t use that range, your body adapts by tightening the surrounding tissue. You''re not "losing" flexibility. You''re training your body to be stiff by never asking it to be flexible. The good news: mobility returns faster than you think. Five minutes of daily mobility work can restore range of motion you haven''t had in years. Your body is waiting for permission to move again.',
'Aisha, 21, couldn''t touch her toes. Hadn''t been able to since she was 14. She thought she was "just not flexible." She started doing 5 minutes of basic mobility every morning — hip circles, shoulder rolls, hamstring stretches. Not forcing anything, just exploring her range. After 2 weeks, she touched her shins. After a month, her ankles. After 6 weeks, her toes. She cried the first time. She''d been convinced her body was permanently limited. It wasn''t. It had just been waiting for her to ask it to move.',
'Stretching aggressively to "force" flexibility. Pain is your body''s signal to stop, not push harder. Forcing your body past its current limits tears tissue and makes you tighter, not looser. Real mobility comes from consistent, gentle exploration of your range — not from one aggressive session. Spend 5 minutes daily moving to your comfortable edge, breathing, and waiting. Your nervous system will gradually release tension as it realizes movement is safe. Force creates resistance. Patience creates progress.',
'Research on proprioception and range of motion shows that stiffness is largely neurological — your nervous system restricts range to protect joints it perceives as unstable or unused. Daily mobility work "teaches" your nervous system that the full range is safe, reducing protective muscle tension within 2-4 weeks. The mechanism: gentle, repeated movement at end-range activates mechanoreceptors that signal safety to the brain, triggering relaxation of protective muscle tone. Flexibility is less about muscle length and more about nervous system permission.',
'Right now, do 10 slow shoulder rolls backward — as big and controlled as you can. Then do 10 hip circles in each direction. Move slowly, breathe, notice where you feel tight. Do this every morning for a week. Write down where you felt restriction on day 1. Check again on day 7. Notice the difference.');

-- Note: This file is truncated for demonstration. The complete file would include all 40 lessons
-- following the same pattern for Units 1-5 (8 lessons each).
-- 
-- To complete this file, add lessons 5-8 for Unit 1, then all 8 lessons for Units 2-5
-- following the UUID scheme:
--   Unit 1 Lessons: 33333333-0200-0001-0000-000000000001 through 000000000008
--   Unit 2 Lessons: 33333333-0200-0002-0000-000000000001 through 000000000008
--   Unit 3 Lessons: 33333333-0200-0003-0000-000000000001 through 000000000008
--   Unit 4 Lessons: 33333333-0200-0004-0000-000000000001 through 000000000008
--   Unit 5 Lessons: 33333333-0200-0005-0000-000000000001 through 000000000008


('33333333-0200-0001-0000-000000000005','22222222-0200-0001-0000-000000000000','Walking as Exercise (It Counts)',5,
'Walking doesn''t feel like exercise because it''s not hard. But hard isn''t the only metric that matters. Walking 30 minutes daily reduces heart disease risk by 30-40%, improves mood as effectively as antidepressants in mild depression, and maintains muscle and bone density better than sitting. It''s not sexy. It doesn''t make you sweat. It works anyway. The best exercise is the one you''ll actually do. For most people, that''s walking. Stop dismissing it as "not enough" and start using it consistently. It''s been working for 200,000 years.',
'Ethan, 22, wanted to "get in shape" so he signed up for a gym. He went twice, felt intimidated, quit. He started walking 20 minutes every day instead — just walking, no goal except to move. After a month, he felt noticeably better. After 3 months, he''d lost 4kg without changing his diet. His resting heart rate dropped from 78 to 64. His doctor asked what program he was on. He said: "I walk." His doctor said: "That''s a program. Keep doing it." A year later, Ethan walks 8000-10000 steps daily without thinking about it. He''s in better shape than when he had the gym membership.',
'Thinking walking is just transportation, not exercise. Walking is locomotion — the foundational human movement pattern. Your cardiovascular system, musculoskeletal system, and nervous system all evolved around walking. The fact that it feels easy is a feature, not a bug. Easy means sustainable. Sustainable means you''ll do it for decades. The exercise you do consistently for 20 years beats the exercise you do intensely for 2 months and quit. Walking wins the long game every time.',
'Harvard research tracking 139,000 people found that walking 30 minutes daily (roughly 3000-4000 steps) reduces all-cause mortality by 24% compared to sedentary individuals. The mechanism: walking activates muscle glucose uptake, improves endothelial function (blood vessel health), reduces systemic inflammation, and triggers BDNF release (brain-derived neurotrophic factor) which supports cognitive function and mood. The benefits plateau around 10,000 steps — meaning you don''t need to walk marathons. Thirty minutes is enough.',
'Tomorrow, track your steps for the full day — use your phone or any step tracker. Write the number down. That''s your baseline. For the next 7 days, add 1000 steps to that baseline daily. You don''t need to walk all at once. Break it into chunks. On day 7, compare how you feel to day 0. Write it down.'),

('33333333-0200-0001-0000-000000000006','22222222-0200-0001-0000-000000000000','Movement Snacking Throughout the Day',6,
'Movement snacking is exactly what it sounds like: short bursts of movement throughout the day instead of one long session. Ten squats here, a 3-minute walk there, 30 seconds of stretching between tasks. It adds up faster than you think, and it keeps your metabolism active all day instead of spiking once. Your body doesn''t care if you moved for 30 minutes straight or 10 minutes three times. It cares that you moved. Movement snacking is how you build an active life without "finding time" to exercise.',
'Priya, 23, worked from home and sat 10 hours daily. She couldn''t find 30 minutes for exercise, so she started movement snacking: 10 squats every time she made coffee, a 2-minute walk every time she finished a task, 30-second stretches before every meeting. She tracked nothing. She just moved between things instead of sitting between things. After a month, she realized she was moving 30-40 minutes daily in 2-5 minute chunks without ever "working out." Her energy doubled. Her back pain disappeared. She said the shift was treating movement as a comma, not a period.',
'Thinking movement only counts if it''s a formal exercise session. This is the mentality that keeps people sedentary — they''re waiting for the "right time" to exercise while sitting for 23.5 hours a day. Movement snacking removes the barriers: no time needed, no equipment, no gym, no plan. Just move when the opportunity appears. Two minutes of movement 10 times per day is 20 minutes of movement. That''s more than most people do in a week. Stop waiting for the perfect session. Start snacking on movement.',
'Research from the University of Bath found that breaking up sitting with 2-minute movement breaks every 30 minutes produced better glucose regulation and insulin sensitivity than a single 30-minute exercise session at the start of the day. The mechanism: frequent movement keeps metabolic processes active throughout the day, whereas a single exercise session produces a spike in activity followed by prolonged shutdown during sitting. Your metabolism responds better to consistency than intensity. Movement snacking keeps your engine running all day.',
'Pick 3 daily triggers — making coffee, finishing a task, going to the bathroom — and attach a movement snack to each one: 10 squats, 20 steps, 30-second stretch, anything. Do this for 3 days. Don''t track it. Just do it when the trigger happens. On day 3, estimate how much total movement you got from snacking. It''s more than you think.'),

('33333333-0200-0001-0000-000000000007','22222222-0200-0001-0000-000000000000','Building Consistency Over Intensity',7,
'The exercise that changes your life isn''t the hardest workout you''ve ever done — it''s the one you do 200 times. Intensity gets attention. Consistency builds results. Most people fail at fitness because they go too hard too fast, burn out, and quit. They mistake soreness for progress and exhaustion for effort. Real progress comes from showing up regularly at a sustainable intensity, not from destroying yourself once and recovering for a week. Build the habit first. Intensity comes later, after consistency is non-negotiable.',
'Noah, 20, tried to go from zero exercise to 6-day-a-week intense workouts. He lasted 9 days, was too sore to move on day 10, and quit. Six months later he tried again: 15 minutes of easy movement, 3 days a week. Too easy to fail. After a month it became automatic. After 3 months he naturally increased to 4 days, then 5, then 30 minutes. A year later he''s training 5 days a week consistently and actually enjoying it. He said the difference was simple: he stopped trying to be impressive and started trying to be consistent. Consistency won.',
'Starting with an intensity you can''t sustain and calling it commitment. Intensity without consistency is just a hard workout. Consistency without intensity is a fitness lifestyle. You can always add intensity to a consistent habit. You can''t add consistency to an unsustainable intensity. Start easier than you think you should. If it feels too easy, that''s correct — you''re building the habit, not testing your limits. The goal for month one is: "I''m someone who moves 3 times a week." Once that''s true, everything else is just turning the dial up.',
'Research on habit formation shows that consistency (frequency) predicts long-term behavior change far more strongly than intensity. Studies on exercise adherence show that people who start with moderate intensity (50-60% max effort) have 3x higher 12-month adherence rates than those who start with high intensity (80%+ effort). The mechanism: sustainable intensity builds positive associations with exercise (enjoyment, energy, confidence), while unsustainable intensity builds negative associations (pain, exhaustion, failure). Your brain learns whether exercise is rewarding or punishing in the first 30 days.',
'Choose an intensity level that feels almost too easy — a walk you could do every day without thinking about it, a workout that leaves you energized instead of exhausted. Do it 3 times this week. Rate your motivation to do it again after each session (1-10). If your average motivation is below 7, you''re going too hard. The goal is to build something you want to repeat, not something you have to force yourself through.'),

('33333333-0200-0001-0000-000000000008','22222222-0200-0001-0000-000000000000','Your First Week of Daily Movement',8,
'The first week of daily movement isn''t about fitness — it''s about identity. You''re proving to yourself that you''re someone who moves every day. The intensity doesn''t matter. The duration doesn''t matter. What matters is the streak. Seven days of 5-minute walks builds more momentum than one day of a 60-minute workout. By day 7, you''ve rewired your brain''s expectation: movement is what you do now. That shift — from "I should move" to "I move" — is the foundation everything else is built on.',
'Lily, 21, committed to 7 days of movement — any movement, any duration, just had to happen every day. Day 1 was a 10-minute walk. Day 2 was 5 minutes of stretching because she had no time. Day 3 was 20 minutes walking because she felt like it. By day 7, she''d moved every day for a week — something she''d never done in her life. She said the biggest shift was mental: she went from "I need to find time to exercise" to "I move every day, just figure out how." That reframe changed everything. Three months later, her streak is at 90 days. She''s missed work, meals, and sleep. She hasn''t missed movement.',
'Breaking the streak in the first week because one day was "too busy" or "didn''t count." There is no such thing as too busy for 5 minutes. And everything counts — a walk, a stretch, squats while brushing your teeth. The first week is not about building fitness. It''s about building proof that you can do this. If you break the streak in week one, you''re teaching your brain that movement is optional and negotiable. If you protect the streak in week one, you''re teaching your brain that movement is non-negotiable. Choose carefully. That lesson sticks.',
'Research on habit formation by Phillippa Lally at University College London found that it takes an average of 66 days for a behavior to become automatic — but the strongest predictor of long-term habit formation is consistency in the first 2 weeks. Missing a day in week one reduces the likelihood of the habit sticking by 61%. The mechanism: the brain forms habits by encoding behavioral sequences in the basal ganglia. Consistency in the early phase creates a strong neural pattern. Inconsistency creates a weak one. Your first week determines whether this becomes a habit or another failed attempt.',
'Commit to 7 consecutive days of movement starting tomorrow. Minimum 5 minutes per day, any kind of movement counts. Track it with a check mark each day. On day 7, write one sentence about how it feels to have a 7-day movement streak. That feeling is what consistency builds.');


-- ============================================================
-- FITNESS — Unit 5: Recovery & Longevity
-- ============================================================
INSERT INTO lessons (id, unit_id, title, display_order, card_concept, card_example, card_mistake, card_science, card_challenge) VALUES
('33333333-0200-0005-0000-000000000001','22222222-0200-0005-0000-000000000000','Sleep Is the Ultimate Performance Drug',1,
'Sleep is not a break from performance — it''s where performance is built. Every adaptation your body makes to exercise happens during sleep: muscle repair, hormone regulation, nervous system recovery, memory consolidation. You can train perfectly and eat perfectly, but if you''re sleeping 5 hours a night, you''re building on quicksand. Sleep is not a luxury or a nice-to-have. It''s the foundation. Without it, everything else — strength, endurance, focus, recovery — falls apart. The athletes who sleep 8+ hours consistently outlast the ones who train harder but sleep less. Every time.',
'James, 21, was training 6 days a week, eating clean, doing everything "right" — but his lifts weren''t going up. He was stuck for 3 months. Frustrated. His coach asked one question: "How much do you sleep?" James said 5-6 hours. His coach said: "Sleep 8 hours for two weeks. Change nothing else." James thought it was a waste of time but tried it. Week one: his squat went up 5kg. Week two: another 5kg. His bench press jumped 7.5kg. He''d been training hard for months with zero progress. Two weeks of sleep and everything moved. He said: "I thought sleep was for rest days. Turns out rest days are for sleep."',
'Thinking you can "catch up" on sleep on weekends or that 6 hours is "enough" if you feel fine. Your body doesn''t catch up on sleep — it accumulates damage when you don''t get enough. Feeling fine on 6 hours doesn''t mean your body is performing optimally; it means you''ve adapted to operating below baseline. Studies show that people sleeping 6 hours per night for two weeks perform as poorly on cognitive and physical tests as people who stayed awake for 48 hours straight — but they don''t feel impaired. You can''t feel sleep debt accurately. You just underperform and call it normal.',
'Research from Stanford University tracking athletes showed that extending sleep to 8-10 hours per night improved sprint times by 5%, shooting accuracy by 9%, and reaction times by 12%. The mechanism: during deep sleep, your body releases growth hormone (which repairs muscle), consolidates motor learning (which improves technique), and clears metabolic waste from the brain (which restores cognitive function). Sleep deprivation suppresses protein synthesis, increases cortisol (which breaks down muscle), and reduces testosterone (which builds it). Training breaks you down. Sleep builds you back up. Without enough sleep, you''re just breaking down.',
'Tonight, set a bedtime alarm for 8 hours before you need to wake up. Not a wake-up alarm — a bedtime alarm. When it goes off, stop what you''re doing and go to bed. Do this for 7 nights. On day 7, write down how you feel compared to your normal schedule: energy, mood, focus, soreness. That contrast is the cost of chronic under-sleeping.'),

('33333333-0200-0005-0000-000000000002','22222222-0200-0005-0000-000000000000','Why Rest Days Make You Stronger',2,
'Rest days are not off days — they''re when your body does the work. Exercise is the stimulus. Recovery is the adaptation. You don''t build muscle in the gym. You break it down in the gym. You build it while you rest. If you train every day without rest, you''re just accumulating damage without giving your body time to repair and upgrade. The result: stagnation, overtraining, injury. Rest days are not laziness. They''re strategic. The people who rest intentionally get stronger faster than the people who train relentlessly. Every time.',
'Mia, 22, was training 7 days a week because she thought "more is better." She was always sore, always tired, and her performance was stuck. Her lifts hadn''t increased in 2 months. She felt like she was working harder than everyone but getting worse results. Her trainer forced her to take 2 full rest days per week. She hated it. Felt guilty. Week one: nothing changed. Week two: she hit a PR on her deadlift. Week three: another PR on squats. After a month, she''d broken through every plateau. She said the shift was mental: she stopped measuring effort by how sore she was and started measuring progress by how much stronger she got. Rest days made her stronger than training days ever did.',
'Thinking soreness equals progress and rest equals wasting time. Soreness is just inflammation — it''s not a reliable indicator of growth. Rest is when growth happens. Your muscles repair, your nervous system recovers, your glycogen stores refill, your connective tissue adapts. Training 7 days a week means you''re perpetually depleted. Your performance never peaks because you never recover. The goal is not to train as much as possible. It''s to train optimally and recover completely. Rest is not the opposite of progress. It''s half the equation.',
'Research on supercompensation shows that muscles grow stronger during recovery, not during training. The training session depletes muscle glycogen and creates micro-tears. In the 24-72 hours after, your body repairs the damage and adds extra capacity (supercompensation) to handle the stress better next time. If you train again before supercompensation completes, you interrupt the process and train in a depleted state. Studies show that athletes who take 1-2 rest days per week gain strength 20-30% faster than those who train daily. Rest is not lost time. It''s when adaptation happens.',
'This week, take 2 full rest days — meaning no structured training, just walking or light stretching if you want. Pick your 2 hardest training days and rest the day after each one. Track your performance in the workouts that follow your rest days vs the ones that don''t. Notice the difference. That''s what recovery does.'),

('33333333-0200-0005-0000-000000000003','22222222-0200-0005-0000-000000000000','Stretching vs Mobility - The Difference',3,
'Stretching is pulling a muscle to its limit and holding it there. Mobility is teaching your joints to move through their full range with control and strength. Stretching makes you feel loose temporarily. Mobility makes you move better permanently. The difference: stretching is passive — you''re forcing length. Mobility is active — you''re building strength at end-range. A flexible person can touch their toes but can''t control their hamstrings through the full range. A mobile person can move through the full range with strength and stability. Flexibility is range. Mobility is usable range.',
'Kai, 20, could touch his toes easily — always could. But he couldn''t squat deep without his lower back rounding. His hamstrings were flexible, but his hips had no strength or control at the bottom of the range. He switched from static stretching to mobility work: controlled squats, hip CARs (controlled articular rotations), loaded stretches. After 6 weeks, his squat depth improved and his back stopped rounding. He said the difference was simple: stretching made him loose. Mobility made him strong. One felt better in the moment. The other made him move better under load.',
'Spending 20 minutes stretching before a workout thinking it prevents injury. It doesn''t. Static stretching before exercise temporarily reduces power output and doesn''t reduce injury risk. Injury happens when you move into a range you can''t control. Stretching increases range without increasing control — which can make you more injury-prone, not less. Mobility work builds strength and control at end-range, which is what protects joints under load. Pre-workout: mobility work or dynamic stretching. Post-workout: static stretching if you want. But don''t confuse the two.',
'Research published in the Journal of Strength and Conditioning shows that static stretching before exercise reduces power output by 5-8% and has no significant effect on injury prevention. In contrast, mobility training (active end-range strengthening) improves joint stability and reduces injury rates by 30-40% in athletes. The mechanism: mobility work strengthens muscles at end-range positions, which is where most injuries occur. Stretching just makes the muscle longer without making it stronger. Flexibility without strength is instability. Mobility is flexible strength.',
'Right now, do this test: stand on one leg and slowly lower into a single-leg squat as deep as you can with control. Notice where you lose balance or range. That''s a mobility limit, not a flexibility limit. For the next week, do 5 single-leg squats per leg every day, only going as deep as you can control. On day 7, test again. That improvement is mobility building.'),

('33333333-0200-0005-0000-000000000004','22222222-0200-0005-0000-000000000000','Injury Prevention Basics',4,
'Most injuries don''t happen because you moved wrong — they happen because you moved into a range your body wasn''t prepared to handle. A torn hamstring didn''t tear because you sprinted. It tore because you sprinted without training your hamstring to handle that load at that speed. Injury prevention is not avoiding risk. It''s building capacity. Strengthen your weakest links, train movements at the edge of your range with control, and progress load gradually. Injuries happen at the gaps between your strength and your ambition. Close the gaps.',
'Anya, 23, started running and loved it. She went from 0km to 30km per week in a month. Week five, her knee started hurting. Week six, she couldn''t run at all. She thought she had bad knees. Her physio said: "Your knees are fine. You just asked them to do more than they were ready for." She dropped to 10km per week and added single-leg strength work twice a week. After 8 weeks, she was back to 30km per week — pain-free. Her physio told her: "Injuries don''t happen because you''re fragile. They happen because you outpaced your adaptation." Anya now increases volume by 10% per week, max. She hasn''t been injured in 2 years.',
'Thinking injuries are random bad luck or that your body is "fragile." Injuries are not random. They''re predictable. They happen when you apply a load your tissues aren''t conditioned to handle: too much volume too fast, too much intensity without preparation, or repetitive movement without adequate recovery. Calling it bad luck is abdicating responsibility. Calling it fragility is misunderstanding biology. Your body adapts to the demands you place on it — but adaptation takes time. Injuries happen when you skip the adaptation phase.',
'Research on injury biomechanics shows that 70-80% of non-contact injuries occur due to training load errors: increasing volume or intensity too quickly, insufficient recovery, or strength imbalances. A study tracking runners found that those who increased weekly mileage by more than 10% per week had a 30% higher injury rate than those who increased by <10%. The mechanism: tissues (muscles, tendons, ligaments) adapt to load, but adaptation requires time and progressive exposure. Overload without adaptation = injury. The goal is not to avoid load. It''s to build capacity progressively.',
'Pick one movement you do regularly (running, squats, push-ups, etc.). This week, track your volume: how many reps, how much distance, how much weight. Write it down. Next week, increase by no more than 10%. That''s the rule. 10% per week is progress without injury. More than that is borrowing time. Notice how sustainable 10% feels compared to jumping 50% like most people do.'),

('33333333-0200-0005-0000-000000000005','22222222-0200-0005-0000-000000000000','Soreness vs Pain - When to Push, When to Stop',5,
'Soreness is discomfort. Pain is warning. Soreness is a dull, achy feeling in the muscle belly 24-48 hours after training — it means you worked the muscle harder than it''s used to. Pain is sharp, localized, and often shows up during or immediately after movement — it means something is wrong. Soreness improves with movement. Pain gets worse. Soreness is symmetric (both legs sore). Pain is often asymmetric (one knee hurts). Training through soreness is fine. Training through pain is how you turn a small issue into a big injury. Learn the difference. Your training longevity depends on it.',
'Luca, 21, felt sharp pain in his right shoulder during bench press. He ignored it, pushed through, finished the set. Next week, the pain was worse. He kept training. Third week, he couldn''t lift his arm above his head. He stopped training for 3 months to recover. His physio told him: "You turned a 2-week issue into a 3-month injury by ignoring the signal." A year later, Luca felt a similar sharp pain in his hip during squats. He stopped immediately, rested for a week, and returned pain-free. He said the difference was simple: soreness is feedback, pain is warning. Feedback you push through. Warnings you listen to.',
'Training through sharp pain because you don''t want to "lose progress" or seem weak. This is ego-driven stupidity. You lose more progress from a 3-month injury than from a 1-week break. Pain is your body''s alarm system — it''s telling you something is at risk. Training through pain doesn''t make you tough. It makes you injured. Another mistake: thinking all soreness is dangerous and avoiding any discomfort. Soreness is normal. It''s how muscles adapt. If you avoid soreness, you avoid progress. The rule: dull ache in the muscle = fine. Sharp, localized pain in a joint or tendon = stop.',
'Research distinguishes between delayed onset muscle soreness (DOMS) — caused by eccentric muscle damage and inflammatory response — and acute pain from tissue injury. DOMS peaks 24-72 hours post-exercise, improves with movement, and is bilateral. Acute injury pain is sharp, worsens with load, and is often asymmetric. Studies show that training through DOMS is safe and can reduce soreness duration. Training through joint or tendon pain increases injury severity by 300-400% and extends recovery time significantly. Pain is not weakness. It''s information. Use it.',
'During your next workout, check in with every movement. Ask: Is this soreness (dull, achy, in the muscle) or pain (sharp, localized, in a joint or tendon)? If it''s soreness, continue. If it''s pain, stop that movement, try something else, and monitor. Write down what you felt and how you responded. That awareness is the skill that keeps you training for decades.'),

('33333333-0200-0005-0000-000000000006','22222222-0200-0005-0000-000000000000','Hydration - More Important Than You Think',6,
'Your body is 60% water. Your muscles are 75% water. Your brain is 73% water. When you''re dehydrated, everything works worse: strength drops, endurance drops, focus drops, recovery slows. Dehydration as low as 2% of body weight reduces physical performance by 10-15% and cognitive performance by 10-20%. Most people walk around mildly dehydrated all day and wonder why they feel tired, sluggish, and weak. Water is not optional. It''s the most performance-enhancing substance you have access to, and it''s free. Drink it.',
'Elena, 20, was always tired by 2pm — every single day. She''d drink coffee, feel better for an hour, then crash again. She thought she needed more sleep. Her roommate noticed she drank maybe 2 glasses of water per day total. Elena started drinking 2 liters daily — just water, nothing else. Within 3 days, her 2pm crash disappeared. She had more energy at 5pm than she used to have at 10am. She said: "I thought I was tired. I was just thirsty for six months straight." Her training performance improved within a week. She''s lifted PRs in every lift since she started hydrating properly. She said the difference felt like taking a performance drug.',
'Waiting until you''re thirsty to drink. Thirst is a late-stage signal — by the time you feel thirsty, you''re already 1-2% dehydrated and your performance has dropped. Another mistake: drinking only during workouts. Hydration is a 24-hour process. Drinking 1 liter during your workout doesn''t fix the 8 hours of under-hydration before it. Your body doesn''t store water like a camel — it needs consistent intake throughout the day. Drink before you''re thirsty. Drink when you wake up, between meals, before and after training, in the evening. Make it automatic.',
'Research from the University of Connecticut shows that even mild dehydration (1.5% body weight loss) impairs mood, increases perception of task difficulty, reduces endurance by 10-12%, and reduces maximal strength by 5-8%. The mechanism: dehydration reduces blood volume, which reduces oxygen delivery to muscles and the brain. It also impairs thermoregulation (heat management), increases heart rate, and slows muscle recovery. Hydration is not about avoiding thirst — it''s about optimizing performance. A 2% improvement from proper hydration is the difference between a PR and a plateau.',
'Tomorrow, fill a 1-liter water bottle in the morning. Your goal: finish it by lunch. Refill it. Finish it by dinner. That''s 2 liters — baseline hydration for most people. Track how you feel at the end of the day: energy, focus, training performance. Compare it to your normal under-hydrated baseline. That difference is what water does.'),

('33333333-0200-0005-0000-000000000007','22222222-0200-0005-0000-000000000000','The 10-Year Fitness Plan',7,
'Most people treat fitness like a sprint: train hard for 3 months, burn out, quit, repeat in a year. The people who transform their lives treat it like a decade-long build. The goal isn''t to be shredded by summer. It''s to be stronger, healthier, and more capable at 35 than you were at 25. That requires a completely different strategy: sustainable intensity, patience with progress, and a long-term identity shift. You''re not "getting in shape." You''re becoming someone who trains for the rest of their life. That mindset changes everything. The 10-year plan beats the 90-day plan every time.',
'Daniel, 24, tried every fitness trend for 6 years: CrossFit for 3 months, bodybuilding for 4 months, powerlifting for 2 months, running for 6 weeks. Every time, he''d go hard, see quick results, burn out, and quit. At 24, he felt worse than at 18. He tried something different: train 3 days per week, moderate intensity, no endpoint. Just build a life where training is normal. Two years later, he''s in the best shape of his life — and he''s not stopping. He said the difference was this: "I used to train to achieve a goal. Now I train because it''s what I do. The goal is to still be doing this at 40." That reframe unlocked everything.',
'Setting short-term outcome goals (lose 10kg, bench 100kg, run a 5k) as your only motivation. Outcome goals are useful for direction, but they''re terrible for sustainability. You hit the goal, you celebrate, you stop training. Or you don''t hit the goal, you feel like a failure, you stop training. Either way, you stop. The alternative: process goals. "I train 3 times per week." "I walk 8000 steps daily." "I sleep 8 hours per night." Process goals have no endpoint. They''re identity-based. You don''t complete them — you become them. That''s what lasts.',
'Research on behavior change shows that identity-based goals (e.g., "I am a person who trains") produce significantly higher long-term adherence than outcome-based goals (e.g., "I want to lose 10kg"). A study tracking 1000+ people over 5 years found that those who adopted a fitness identity ("I am a runner" vs "I want to run a 5k") had 2-3x higher sustained activity levels. The mechanism: identity drives behavior. Outcomes are temporary. Identity is permanent. If your goal is an outcome, you stop when you achieve it. If your goal is an identity, you never stop.',
'Write this sentence and fill in the blank: "In 10 years, I want to be someone who ___." Not an outcome (weighs X, lifts X, looks like X). An identity. Example: "In 10 years, I want to be someone who trains consistently and feels strong in my body." Read it once per week. That''s your North Star. Everything else is just the path.'),

('33333333-0200-0005-0000-000000000008','22222222-0200-0005-0000-000000000000','Your Body at 60 Starts Today',8,
'The body you have at 60 is being built right now. Every decision you make today — movement, food, sleep, recovery — is either investing in your future capacity or borrowing against it. Muscle mass peaks in your 30s and declines 3-8% per decade after 40 — unless you train to maintain it. Bone density peaks in your early 30s and declines steadily — unless you load your skeleton with resistance training. Cardiovascular capacity, mobility, balance, all decline — unless you use them. Your 60-year-old self is counting on your 20-year-old self to build a foundation. Don''t let them down.',
'Sophia, 22, met a 68-year-old man at her gym who was squatting 100kg, running 5k twice a week, and moving better than most 30-year-olds. She asked him how. He said: "I started training at 25 and never stopped. Everyone my age is on medication, can''t climb stairs, needs help getting up. I''m not special. I just moved my body for 40 years." Sophia realized she''d been thinking about fitness as "looking good now." That man was thinking about it as "functioning well at 70." She said that conversation completely reframed her training. She''s not training for summer. She''s training for the next 50 years. That mindset shift changed everything.',
'Thinking your 20s are "too early" to care about long-term health. The opposite is true. Your 20s are when you build the foundation. Muscle mass, bone density, cardiovascular capacity, joint health — all peak in your 20s and 30s. What you build now, you spend the rest of your life maintaining. If you don''t build it now, you have nothing to maintain later. Starting at 50 is harder than maintaining from 25. The time to start is now, not when you "need to" in 20 years. By then, you''re playing catch-up instead of staying ahead.',
'Research shows that lean muscle mass and bone mineral density built in your 20s and 30s are the strongest predictors of physical function and independence after age 65. A study published in The Lancet found that individuals who maintained regular resistance training from their 20s onward had 40-50% lower risk of mobility limitations, falls, and fractures in their 60s and 70s. The mechanism: sarcopenia (age-related muscle loss) and osteoporosis (bone density loss) are not inevitable — they''re preventable with consistent training. Your body at 70 is the result of what you did at 25, 35, 45, 55. Start now.',
'Right now, imagine yourself at 65. Picture what you want to be able to do: hike, play with grandkids, travel, move without pain, live independently. Write down 3 specific things. Now ask: what does your 25-year-old self need to do today to make that possible? That''s your training purpose. Not abs. Not aesthetics. Function at 65. Train for that.');
