/** @type {import('jest').Config} */
module.exports = {
  testEnvironment: 'node',
  transform: {
    '^.+\\.tsx?$': ['babel-jest', { presets: ['babel-preset-expo'] }],
  },
  transformIgnorePatterns: [
    'node_modules/(?!(react-native-url-polyfill|@supabase|@react-native-async-storage)/)',
  ],
  testMatch: [
    '**/__tests__/rex*.test.ts',
    '**/__tests__/i18nService.test.ts',
    '**/__tests__/languageService.test.ts',
    '**/__tests__/lessonService.test.ts',
    '**/__tests__/relapseService.test.ts',
    '**/__tests__/freezeService.test.ts',
    '**/__tests__/capsuleService.test.ts',
    '**/__tests__/widgetService.test.ts',
    '**/__tests__/wrappedService.test.ts',
    '**/__tests__/rexMemoryService.test.ts',
    '**/__tests__/extractMemories.test.ts',
    '**/__tests__/briefingService.test.ts',
    '**/__tests__/mentalStateRoundTrip.test.ts',
    '**/__tests__/debriefService.test.ts',
    '**/__tests__/sosService.test.ts',
    '**/__tests__/breathingExercise.test.ts',
    '**/__tests__/partnerService.test.ts',
    '**/__tests__/reportService.test.ts',
    '**/__tests__/briefingXpAward.test.ts',
    '**/__tests__/speakingMetrics.test.ts',
    '**/__tests__/analyzeSpeech.test.ts',
    '**/__tests__/speakingService.test.ts',
  ],
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json'],
  moduleNameMapper: {
    '^expo-localization$': '<rootDir>/src/__mocks__/expo-localization.ts',
    '^expo-notifications$': '<rootDir>/src/__mocks__/empty.ts',
    '^@react-native-async-storage/async-storage$': '<rootDir>/src/__mocks__/async-storage.ts',
    '^i18next$': '<rootDir>/src/__mocks__/i18next.ts',
    '^react-i18next$': '<rootDir>/src/__mocks__/react-i18next.ts',
    '^../../locales/(.*)$': '<rootDir>/src/__mocks__/translation.ts',
    '^../../../locales/(.*)$': '<rootDir>/src/__mocks__/translation.ts',
    '^react-native-url-polyfill/auto$': '<rootDir>/src/__mocks__/empty.ts',
    '^react-native-url-polyfill$': '<rootDir>/src/__mocks__/empty.ts',
    '^../services/supabaseClient$': '<rootDir>/src/__mocks__/supabaseClient.ts',
    '^../../services/supabaseClient$': '<rootDir>/src/__mocks__/supabaseClient.ts',
    '^./supabaseClient$': '<rootDir>/src/__mocks__/supabaseClient.ts',
    '^../services/progressService$': '<rootDir>/src/__mocks__/progressService.ts',
    '^../../services/progressService$': '<rootDir>/src/__mocks__/progressService.ts',
    '^./progressService$': '<rootDir>/src/__mocks__/progressService.ts',
    '^../services/notificationService$': '<rootDir>/src/__mocks__/notificationService.ts',
    '^../../services/notificationService$': '<rootDir>/src/__mocks__/notificationService.ts',
    '^./notificationService$': '<rootDir>/src/__mocks__/notificationService.ts',
  },
};
